[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#131313"
textColor = "#e8e2d9"
font = "sans serif"